// <auto-generated />
namespace CamelsClub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class init11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init11));
        
        string IMigrationMetadata.Id
        {
            get { return "202006162048041_init11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
