//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamelsClub.Localization.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CamelsClub.Localization.Shared.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الاضافة بنجاح.
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم تقييم هذا الجمل من قبل.
        /// </summary>
        public static string camelreviewedbefore {
            get {
                return ResourceManager.GetString("camelreviewedbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يقل رقم مواصفات الجمل الذي تم إدخاله عن إجمالي عدد مواصفات التحكيم.
        /// </summary>
        public static string camelspecificationcount {
            get {
                return ResourceManager.GetString("camelspecificationcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصائص تقيم الجمل لا يجب ان تكون فارغة.
        /// </summary>
        public static string CamelsSpecificationRequired {
            get {
                return ResourceManager.GetString("CamelsSpecificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا  يزيد إجمالي ملخص مراجعة مواصفات الجمال عن 100٪.
        /// </summary>
        public static string CamelTotalsSpecifcationsValue {
            get {
                return ResourceManager.GetString("CamelTotalsSpecifcationsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم باختيار رئيس تمييز واحد.
        /// </summary>
        public static string ChooseOneBossChecker {
            get {
                return ResourceManager.GetString("ChooseOneBossChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم باختيار رئيس تحكيم واحد.
        /// </summary>
        public static string ChooseOneReferee {
            get {
                return ResourceManager.GetString("ChooseOneReferee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الكود مستخدم من قبل.
        /// </summary>
        public static string CodeUsedBefore {
            get {
                return ResourceManager.GetString("CodeUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية إضافة التعليق بنجاح.
        /// </summary>
        public static string CommentAddedSuccessfully {
            get {
                return ResourceManager.GetString("CommentAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية حذف المنشور بنجاح.
        /// </summary>
        public static string CommentDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CommentDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا التعليق غير موجود.
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية تعديل التعليق بنبجاح.
        /// </summary>
        public static string CommentUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("CommentUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اعتماد النتيجة لمنشئ المسابقة.
        /// </summary>
        public static string CompetitionIsFinished {
            get {
                return ResourceManager.GetString("CompetitionIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية حذف البيانات بنجاح.
        /// </summary>
        public static string DataDeleted {
            get {
                return ResourceManager.GetString("DataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية تحميل البيانات بنجاج.
        /// </summary>
        public static string DataLoaded {
            get {
                return ResourceManager.GetString("DataLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البريد الإلكتروني موجود من قبل.
        /// </summary>
        public static string EmailAreadyExist {
            get {
                return ResourceManager.GetString("EmailAreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا لقد تمت إضافة هذه العناصر من قبل.
        /// </summary>
        public static string ExistedItems {
            get {
                return ResourceManager.GetString("ExistedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية قبول طلب المتابعة بنجاح.
        /// </summary>
        public static string FriendRequestApporoved {
            get {
                return ResourceManager.GetString("FriendRequestApporoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الكود غير صحيح.
        /// </summary>
        public static string InvaildCode {
            get {
                return ResourceManager.GetString("InvaildCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون تاريخ انتهاء المسابقة أكبر من أو يساوي تاريخ البدء.
        /// </summary>
        public static string InvalidCompetitionDates {
            get {
                return ResourceManager.GetString("InvalidCompetitionDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون تاريخ بدء المسابقة أكبر من أو يساوي التاريخ الحالي.
        /// </summary>
        public static string InvalidCompetitionStartDate {
            get {
                return ResourceManager.GetString("InvalidCompetitionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني غير صحيح.
        /// </summary>
        public static string InValidEmail {
            get {
                return ResourceManager.GetString("InValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية يجب ان يحتوي علي ارقام فقط وطوله 10 ارقام.
        /// </summary>
        public static string InValidNID {
            get {
                return ResourceManager.GetString("InValidNID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يبدأ رقم الهاتف بـ (05) ويبلغ طوله 10 أرقام.
        /// </summary>
        public static string InValidPhoneNumber {
            get {
                return ResourceManager.GetString("InValidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة التصويت غير صحيحة.
        /// </summary>
        public static string InvalidVotePercentage {
            get {
                return ResourceManager.GetString("InvalidVotePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد متسابقين ولا يمكنك التعديل.
        /// </summary>
        public static string InvitedUsersJoined {
            get {
                return ResourceManager.GetString("InvitedUsersJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هناك اكثر من رئيس للتمييز.
        /// </summary>
        public static string MoreThanOneCheckerBoss {
            get {
                return ResourceManager.GetString("MoreThanOneCheckerBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هناك اكثر من رئيس للتحكيم.
        /// </summary>
        public static string MoreThanOneRefereeBoss {
            get {
                return ResourceManager.GetString("MoreThanOneRefereeBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العنصر غير موجود.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انت لست  ضمن حكام هذة المسابقة.
        /// </summary>
        public static string NotRefree {
            get {
                return ResourceManager.GetString("NotRefree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الرقم موجود من قبل.
        /// </summary>
        public static string PhoneNumberAreadyExist {
            get {
                return ResourceManager.GetString("PhoneNumberAreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رقم الهاتف.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة المنشور الخاص بك بنجاح.
        /// </summary>
        public static string PostAddedSuccessfully {
            get {
                return ResourceManager.GetString("PostAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف المنشور الخاص بك بنجاح.
        /// </summary>
        public static string PostDeletededSuccessfully {
            get {
                return ResourceManager.GetString("PostDeletededSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المشور غير موجود.
        /// </summary>
        public static string PostNotFound {
            get {
                return ResourceManager.GetString("PostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل المنشور بنجاح.
        /// </summary>
        public static string PostUpdatededSuccessfully {
            get {
                return ResourceManager.GetString("PostUpdatededSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم ليس حكم.
        /// </summary>
        public static string RefereeNotExist {
            get {
                return ResourceManager.GetString("RefereeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب.
        /// </summary>
        public static string RequiredFieldValidation {
            get {
                return ResourceManager.GetString("RequiredFieldValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اجراء التقييم بنجاج.
        /// </summary>
        public static string reviewsubmitsucessfully {
            get {
                return ResourceManager.GetString("reviewsubmitsucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء إرسال الإشعار.
        /// </summary>
        public static string SendingFailure {
            get {
                return ResourceManager.GetString("SendingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد مستقبل للرسالة.
        /// </summary>
        public static string SendMessageToYourself {
            get {
                return ResourceManager.GetString("SendMessageToYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارسال كود الي رقم الهاتف الذي تم ادخاله ,الرجاء التحقق من هاتفك.
        /// </summary>
        public static string SendVerificationCode {
            get {
                return ResourceManager.GetString("SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا حدث خطأ اثناء ارسال الكود الي رقم الهاتف الذي تم ادخاله.
        /// </summary>
        public static string SendVerificationCodeError {
            get {
                return ResourceManager.GetString("SendVerificationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم موجود من قبل اختر اسم جديد.
        /// </summary>
        public static string UserNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لا يوجد مستخدم بهذا الرقم , الرجاء ادخال رقم صحيح.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحقق من الكود بنجاح.
        /// </summary>
        public static string VerfifySucccessfully {
            get {
                return ResourceManager.GetString("VerfifySucccessfully", resourceCulture);
            }
        }
    }
}
